---
title: "Nearshore Network Analysis"
author: "Nick Framsted"
date: "1/5/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(ggpubr)
# changing working directory from /scripts to /tahoe_lab_inc_analysis
knitr::opts_knit$set(root.dir = '..')
```

```{r}
# importing dataset for tahoe city (closest site to the pineland site)
dat_TC <- read_csv("C:/Users/ntframst/Documents/Tahoe_nearshore_network_data/TC.txt")
str(dat_TC)
#View(dat_TC)
```

### plotting temperature (probeT) for TC site
```{r}
# filtering out period of NAs in ProbeT column
dat_TC %>%
  filter(TimeLocal < "2020-10-01 00:00:00") %>%
  ggplot(aes(x = TimeLocal, y = ProbeT)) +
  geom_line()

# violin plot of daily temperatures
dat_TC %>%
  mutate(day = date(TimeLocal)) %>%
  filter(!is.na(ProbeT)) %>%
  ggplot(aes(x = day, y = ProbeT, group = day)) +
  geom_violin() +
  theme_bw(base_size = 20)

# looking at daily scales of temp variability
daily_T <- dat_TC %>%
  mutate(day = date(TimeLocal)) %>%
  group_by(day) %>%
  summarize(avg_T = mean(ProbeT), min_T = min(ProbeT), max_T = max(ProbeT)) %>%
  mutate(range_T = max_T - min_T)
daily_T


# adding in season column to data, grouping rows by season to calculate seasonal average temp standard deviation
seasonal_T <- daily_T %>%
  mutate(season = ifelse(day >= "2019-12-31" & day < "2020-03-01", "W", ifelse(day >= "2020-03-01" & day < "2020-06-01", "Spr", ifelse(day >= "2020-06-01" & day < "2020-09-01", "Sum", "F")))) %>%
  filter(!is.na(range_T)) %>%
  group_by(season) %>%
  summarize(avg_daily_range = mean(range_T), max_daily_range = max(range_T))
seasonal_T


# calculating average june temperatures for planning june 2021 incubation
june_T <- dat_TC %>%
  filter(TimeLocal >= "2020-06-01 00:00:00" & TimeLocal < "2020-07-01 00:00:00") %>%
  summarize(avg_T = mean(ProbeT))

# plotting june temperatures with average june temperature overlayed
dat_TC %>%
  filter(TimeLocal >= "2020-06-01 00:00:00" & TimeLocal < "2020-07-01 00:00:00") %>%
  ggplot(aes(x = TimeLocal, y = ProbeT)) +
  geom_point() +
  geom_hline(aes(yintercept = june_T$avg_T), data = june_T, color = "red")
  
```

Looks like maximum daily flucuations of temperature are on the order of 6.5C in a day and average daily fluctuations are 2-3C, thus temperature treatments should be created accordingly.
