---
title: "210315 Tahoe city Enriched Analysis"
author: "Nick Framsted"
date: "3/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(ggpubr)
library(plotly)
# changing working directory from /scripts to /tahoe_lab_inc_analysis
knitr::opts_knit$set(root.dir = '..')
```


```{r, include = FALSE}
# importing and cleaning up DO data
dat <- read_csv("data/210315_tahoecity_enriched_inc/210316_DO_tahoecity_inc_enriched_R.csv", skip = 1)
str(dat)
#View(dat)


# filtering out rows with error codes, and adding in chamber numbers based the tank and channel number cross referenced against incubation notes
dat_2 <- dat %>%
  filter(Error == 0) %>%
  mutate(chamber = ifelse(SensorID == "125448721", "Chamber 16", ifelse(SensorID == "175401527", "Chamber 13", ifelse(SensorID == "141697176", "Chamber 14", ifelse(SensorID == "190253489", "Chamber 11", ifelse(SensorID == "182196134", "Chamber 9", ifelse(SensorID == "848546098", "Chamber 1", ifelse(SensorID == "50027230", "Chamber 8", ifelse(SensorID == "172345502", "Chamber 12", ifelse(SensorID == "126217967", "Chamber 15", ifelse(SensorID == "175334401", "Chamber 6", ifelse(SensorID == "814963468", "Chamber 7", ifelse(SensorID == "458949207", "Chamber 5", ifelse(SensorID == "24319898", "Chamber 2", ifelse(SensorID == "135332981", "Chamber 3", ifelse(SensorID == "162832118", "Chamber 4", "Chamber 10"))))))))))) ))))) %>%
  mutate(treatment = ifelse(Temp > 6 & Temp < 9, "7C", ifelse(Temp > 8 & Temp < 12, "10C", ifelse(Temp > 12 & Temp < 15, "13C", "16C"))))

head(dat_2)

# double checking this worked
#View(dat_2 %>% select(Channel, Device_Serial, chamber))

# looks like it worked, all chambers are assigned to the correct rows

# renaming oxygen data column and the delta_T columns to include units
dat_2 <- dat_2 %>%
  rename(oxygen = Value, delta_T_min = delta_t, time = Time, date = Date, temp = Temp)
head(dat_2)


# selecting only columns I need
dat_subset <- dat_2 %>%
  select(date, time, delta_T_min, oxygen, temp, chamber, treatment)

# importing in other complementary data associated with chambers
dat_chambers <- read_csv("data/210315_tahoecity_enriched_inc/chamber_wts_enriched_R.csv")
str(dat_chambers)
#View(dat_chambers)

# joining DO data and chamber data by "chamber" column
dat_full <- full_join(dat_subset, dat_chambers, by = "chamber")
#View(dat_full)
# converting oxygen concentration (mg/L) to oxygen mass (mg) by multipying by water volumes in chambers
dat_full <- dat_full %>%
  mutate(oxygen_mass_mg = oxygen * water_volume_L)
```



## Plotting DO and temp in chambers
```{r echo = FALSE}
# making treatment a factor variable and re-ordering it for plots
dat_full$treatment <- factor(dat_subset$treatment, levels = c("7C", "10C", "13C", "16C"))

# plotting Do concentrations in each chamber
DO_conc_plot <- dat_full %>%
  ggplot(aes(x = delta_T_min, y = oxygen, color = chamber)) +
  geom_line(size = 1.5) +
  scale_color_viridis_d() +
  facet_wrap(~treatment) +
  labs(y = expression(Oxygen~Concentration~(mg~L^{-1})), x = "Elapsed Time (min)", title = "Tahoe City Incubation DO") +
  theme_bw(base_size = 20)

DO_conc_plot

ggsave("plots/210315_tahoecity_enriched/210315_tahoecity_DO_conc_plot.png", plot = DO_conc_plot, width = 10, height = 7)

# plotting temperature for each chamber
temp_plot <- dat_full %>%
  ggplot(aes(x = delta_T_min, y = temp, color = chamber)) +
  geom_line(size = 1.5) +
  scale_color_viridis_d() +
  facet_wrap(~treatment) +
  labs(y = expression('Temperature (\u00B0C)'), x = "Elapsed Time (min)", title = "Tahoe City Incubation Temperature") +
  theme_bw(base_size = 20) +
  theme(legend.position = "none")

temp_plot

ggsave("plots/210315_tahoecity_enriched/210315_tahoecity_temp_plot.png", plot = temp_plot, width = 10, height = 7)

# plotting DO mass (mg) for each chamber
DO_mass_plot <- dat_full %>%
  ggplot(aes(x = delta_T_min, y = oxygen_mass_mg, color = chamber)) +
  geom_line(size = 1.5) +
  xlim(70, 285) +
  scale_color_viridis_d() +
  facet_wrap(~treatment) +
  labs(y = expression(Oxygen~Mass~(mg)), x = "Elapsed Time (min)", title = "Tahoe City Incubation DO Mass") +
  theme_bw(base_size = 20) +
  theme(legend.position = "none")

  DO_mass_plot
  
ggsave("plots/210315_tahoecity_enriched/210315_tahoecity_DO_mass_plot.png", plot = DO_mass_plot, width = 10, height = 7)

# making interactive plot with plotly to help identity data points for rate calculations below
p<- plotly::ggplotly(DO_mass_plot)
p
# exporting interactive plot to html
htmlwidgets::saveWidget(as_widget(p), "plots/210315_tahoecity_enriched/210315_tc_DO_mass_plot.html")

```

## Metabolic Rate Calculations
### Tank 1
#### Chamber 9
```{r}
# NEP rate calculations

## the linear portion of the NEP curve is roughly from minute 95 to minute 170 ##
tc_e_9 <- dat_full %>%
  filter(chamber == "Chamber 9" & delta_T_min >= 95 & delta_T_min <= 170)

tc_e_9_NEP_mod <- lm(oxygen_mass_mg~delta_T_min, tc_e_9)
summary(tc_e_9_NEP_mod)
tc_e_9_NEP_mod$coefficients[2]
tc_e_9_NEP_slope <- unname(tc_e_9_NEP_mod$coefficients[2])

# oxygen mass (mg) = 0.01659 * time(minutes) + 0.2537

## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
tc_e_9_NEP <- tc_e_9_NEP_slope * 1440
tc_e_9_NEP

# ER rate calculations
## linear portion of the ER curve is roughly from minute 225 to the end of the incubation.
# This is due to a weird oxygen spike caused by temperature measurements associated with DO calculations reflecting water bath temperatures and not temperatures inside chambers, thus DO msmnts were inflated for this brief period.
# I took slopes of ER curves before and after the erroneous DO spike and averaged the two slopes to get the average ER rate
tc_e_9 <- dat_full %>%
  filter(chamber =="Chamber 9" & delta_T_min >= 225)

tc_e_9_ER_mod <- lm(oxygen_mass_mg~delta_T_min, tc_e_9)
summary(tc_e_9_ER_mod)
tc_e_9_ER_mod$coefficients[2]
tc_e_9_ER_slope <- unname(tc_e_9_ER_mod$coefficients[2])

# oxygen mass (mg) =* time(minutes) + 

## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
tc_e_9_ER <- tc_e_9_ER_slope * 1440
tc_e_9_ER

## checking slope of other section of ER curve to make sure they're the same before and after the anomalous DO spike
tc_e_9 <- dat_full %>%
  filter(chamber =="Chamber 9" & delta_T_min >= 175 & delta_T_min <= 215)
tc_e_9_ER_mod2 <- lm(oxygen_mass_mg~delta_T_min, tc_e_9)
summary(tc_e_9_ER_mod2)
```

#### Chamber 1
```{r}
# NEP rate calculations

## the linear portion of the NEP curve is roughly from minute 95 to minute 170 ##
tc_e_9 <- dat_full %>%
  filter(chamber == "Chamber 9" & delta_T_min >= 95 & delta_T_min <= 170)

tc_e_9_NEP_mod <- lm(oxygen_mass_mg~delta_T_min, tc_e_9)
summary(tc_e_9_NEP_mod)
tc_e_9_NEP_mod$coefficients[2]
tc_e_9_NEP_slope <- unname(tc_e_9_NEP_mod$coefficients[2])

# oxygen mass (mg) = 0.01659 * time(minutes) + 0.2537

## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
tc_e_9_NEP <- tc_e_9_NEP_slope * 1440
tc_e_9_NEP

# ER rate calculations
## linear portion of the ER curve is roughly from minute 225 to the end of the incubation.
# This is due to a weird oxygen spike caused by temperature measurements associated with DO calculations reflecting water bath temperatures and not temperatures inside chambers, thus DO msmnts were inflated for this brief period.
tc_e_9 <- dat_full %>%
  filter(chamber =="Chamber 9" & delta_T_min >= 225)

tc_e_9_ER_mod <- lm(oxygen_mass_mg~delta_T_min, tc_e_9)
summary(tc_e_9_ER_mod)
tc_e_9_ER_mod$coefficients[2]
tc_e_9_ER_slope <- unname(tc_e_9_ER_mod$coefficients[2])

# oxygen mass (mg) =* time(minutes) + 

## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
tc_e_9_ER <- tc_e_9_ER_slope * 1440
tc_e_9_ER
```

