---
title: "210301-210315 Tahoe City Inc"
author: "Nick Framsted"
date: "7/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(ggpubr)
library(plotly)
library(reshape2)
library(DescTools)

# changing working directory from /scripts to /tahoe_lab_inc_analysis
knitr::opts_knit$set(root.dir = '..')
```

# Importing and Processing data
```{r, include = FALSE}
# importing and cleaning up metabolism data from both ambient and enriched incubations
dat_a <- read_csv("data/210301_tahoecity_ambient_inc/210301_TC_ambient_rates.csv")
# changing class of chamber column to be compatible with the other dataframe
dat_a$chamber <- as.character(dat_a$chamber)

# selecting only the columns that I need
dat_a <- dat_a %>%
  select(chamber, temp_C, total_DW_g, total_AFDW_g, rock_SA_m2, NEP_mg_d:nutrient_trt)

dat_e <- read_csv("data/210315_tahoecity_enriched_inc/210315_TC_enriched_rates.csv")

# selecting only the columns that I need
dat_e <- dat_e %>%
  select(chamber, total_DW_g, total_AFDW_g, rock_SA_m2, NEP_mg_d:nutrient_trt)

# binding the rows of the two dataframes together
dat <- bind_rows(dat_a, dat_e)
# adding in nutrient enriched dummy variable column (0 = ambient, 1 = enriched nutrients)
dat <- dat %>%
  mutate(nutrients = ifelse(nutrient_trt == "ambient", 0, 1))
#View(dat)

```

# Regression of AFDW-normalized GPP with temperature and nutrients
```{r}
# linear model of GPP and temp
GPP_AFDW_mod <- lm(GPP_mgO2_d_gAFDW ~ temp_C*nutrients, dat)
summary(GPP_AFDW_mod)

dat %>%
  ggplot(aes(x = temp_C, y = GPP_mgO2_d_gAFDW, color = nutrient_trt)) +
  geom_point(shape = 19, size = 2) +
  geom_smooth(method = "lm") +
  stat_regline_equation() +
  theme_classic() +
  labs(title = "GPP response to Temperature",
      x = expression('Temperature (\u00B0C)'),
      y = expression(GPP~(mgO[2]~day^{-1}~gAFDW^{-1})))
```


# Regression of surface area-normalized GPP with temperature and nutrients
```{r}
# linear model of GPP and temp
GPP_SA_mod <- lm(GPP_mgO2_d_m2 ~ temp_C*nutrients, dat)
summary(GPP_SA_mod)

dat %>%
  ggplot(aes(x = temp_C, y = GPP_mgO2_d_m2, color = nutrient_trt)) +
  geom_point(shape = 19, size = 2) +
  geom_smooth(method = "lm") +
  stat_regline_equation() +
  theme_classic() +
  labs(title = "GPP response to Temperature",
      x = expression('Temperature (\u00B0C)'),
      y = expression(GPP~(mgO[2]~day^{-1}~m^{-2})))
```

# Regression of ER (AFDW-normalized) with temperature and nutrients
```{r}
ER_AFDW_mod <- lm(ER_mgO2_d_gAFDW ~ temp_C*nutrients, dat)
summary(ER_AFDW_mod)

dat %>%
  ggplot(aes(x = temp_C, y = ER_mgO2_d_gAFDW, color = nutrient_trt)) +
  geom_point(shape = 19, size = 2) +
  geom_smooth(method = "lm") +
  stat_regline_equation() +
  theme_classic() +
  labs(title = "ER response to Temperature",
      x = expression('Temperature (\u00B0C)'),
      y = expression(ER~(mgO[2]~day^{-1}~gAFDW^{-1})))
```

# Regression of surface area-normalized ER with temp and nutrients
```{r}
# linear model of GPP and temp
ER_SA_mod <- lm(ER_mgO2_d_m2 ~ temp_C*nutrients, dat)
summary(ER_SA_mod)

dat %>%
  ggplot(aes(x = temp_C, y = ER_mgO2_d_m2, color = nutrient_trt)) +
  geom_point(shape = 19, size = 2) +
  geom_smooth(method = "lm") +
  stat_regline_equation() +
  theme_classic() +
  labs(title = "ER response to Temperature",
      x = expression('Temperature (\u00B0C)'),
      y = expression(ER~(mgO[2]~day^{-1}~m^{-2})))
```

