---
title: "210407 Pineland Ambient"
author: "Nick Framsted"
date: "5/7/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(ggpubr)
library(plotly)
library(reshape2)
library(DescTools)

# changing working directory from /scripts to /tahoe_lab_inc_analysis
knitr::opts_knit$set(root.dir = '..')
```

# Importing and Processing data
```{r, include = FALSE}
# importing and cleaning up DO data
dat <- read_csv("data/210407_pineland_ambient/210407_pineland_ambient_DO_R.csv", skip = 1)
#str(dat)
#View(dat)


# filtering out rows with error codes, and adding in chamber numbers based the tank and channel number cross referenced against incubation notes
## double checked for correctness on 7/6/21 NTF

dat_2 <- dat %>%
  filter(Error == 0) %>%
  mutate(
    chamber = case_when(
    tank_channel == "Tank 1_1"  ~ "6",
    tank_channel == "Tank 1_2"  ~ "9",
    tank_channel == "Tank 1_3" ~ "2",
    tank_channel == "Tank 1_4" ~ "11",
    tank_channel == "Tank 2_1" ~ "13",
    tank_channel == "Tank 2_2" ~ "15",
    tank_channel == "Tank 2_3" ~ "4",
    tank_channel == "Tank 2_4" ~ "16",
    tank_channel == "Tank 3_1" ~ "12",
    tank_channel == "Tank 3_2" ~ "14",
    tank_channel == "Tank 3_3" ~ "8",
    tank_channel == "Tank 3_4" ~ "1",
    tank_channel == "Tank 4_1" ~ "3",
    tank_channel == "Tank 4_2" ~ "7",
    tank_channel == "Tank 4_3" ~ "10",
    tank_channel == "Tank 4_4" ~ "5",
  )) %>%
   mutate(treatment = ifelse(Device_Serial == "Tank 2", "7C", ifelse(Device_Serial == "Tank 1", "10C", ifelse(Device_Serial == "Tank 3", "13C", "16C"))))
 
#View(dat_2)
#head(dat_2)



# double checking this worked
#dat_2$chamber <- as.factor(dat_2$chamber)
#levels(dat_2$chamber)
#str(dat_2)
#summary(dat_2)

#View(dat_2 %>% select(Channel, Device_Serial, chamber))

# looks like it worked, all chambers are assigned to the correct rows

# renaming oxygen data column and the delta_T columns to include units
dat_2 <- dat_2 %>%
  rename(oxygen = Value, delta_T_min = delta_t, time = Time, date = Date, temp = Temp)
head(dat_2)


# selecting only columns I need, and changing chamber column from a factor to a double
dat_subset <- dat_2 %>%
  select(date, time, delta_T_min, oxygen, temp, chamber, treatment)

  dat_subset$chamber <- as.numeric(dat_subset$chamber)

# importing in other complementary data associated with chambers
dat_chambers <- read_csv("data/210407_pineland_ambient/210407_pineland_datasheet_R.csv")
#str(dat_chambers)
dat_chambers$chamber <- as.numeric(dat_chambers$chamber)
#View(dat_chambers)

# joining DO data and chamber data by "chamber" column
dat_full <- full_join(dat_subset, dat_chambers, by = "chamber")
#View(dat_full)
# converting oxygen concentration (mg/L) to oxygen mass (mg) by multipying by water volumes in chambers
dat_full <- dat_full %>%
  mutate(oxygen_mass_mg = oxygen * water_volume_L)
#View(dat_full)
```

## Plotting DO and temp in chambers
```{r echo = FALSE}
# making treatment a factor variable and re-ordering it for plots
dat_full$treatment <- factor(dat_full$treatment, levels = c("7C", "10C", "13C", "16C"))
# making chamber a factor so that it's a discrete value for coloring datapoints in plot
dat_full$chamber <- as.factor(dat_full$chamber)

# plotting Do concentrations in each chamber
DO_conc_plot <- dat_full %>%
  ggplot(aes(x = delta_T_min, y = oxygen, color = chamber)) +
  geom_line(size = 1.5) +
  scale_color_viridis_d() +
  facet_wrap(~treatment) +
  labs(y = expression(Oxygen~Concentration~(mg~L^{-1})), x = "Elapsed Time (min)", title = "Pineland Ambient Incubation DO") +
  theme_bw(base_size = 20)

DO_conc_plot

ggsave("plots/210407_pineland_ambient/210407_pineland_ambient_DO_conc_plot.png", plot = DO_conc_plot, width = 10, height = 7)

# plotting temperature for each chamber
temp_plot <- dat_full %>%
  ggplot(aes(x = delta_T_min, y = temp, color = chamber)) +
  geom_line(size = 1.5) +
  scale_color_viridis_d() +
  facet_wrap(~treatment) +
  labs(y = expression('Temperature (\u00B0C)'), x = "Elapsed Time (min)", title = "Pineland Ambient Incubation Temperature") +
  theme_bw(base_size = 20) +
  theme(legend.position = "none")

temp_plot

ggsave("plots/210407_pineland_ambient/210407_pineland_ambient_temp_plot.png", plot = temp_plot, width = 10, height = 7)

# plotting DO mass (mg) for each chamber
DO_mass_plot <- dat_full %>%
  ggplot(aes(x = delta_T_min, y = oxygen_mass_mg, color = chamber)) +
  geom_line(size = 1.5) +
  xlim(70, 285) +
  scale_color_viridis_d() +
  facet_wrap(~treatment) +
  labs(y = expression(Oxygen~Mass~(mg)), x = "Elapsed Time (min)", title = "Pineland Ambient Incubation DO Mass") +
  theme_bw(base_size = 20) +
  theme(legend.position = "none")

  DO_mass_plot
  
ggsave("plots/210407_pineland_ambient/210407_pineland_ambient_DO_mass_plot.png", plot = DO_mass_plot, width = 10, height = 7)

# making interactive plot with plotly to help identity data points for rate calculations below
p<- plotly::ggplotly(DO_mass_plot)
p
# exporting interactive plot to html
htmlwidgets::saveWidget(as_widget(p), "plots/210407_pineland_ambient/210407_pineland_ambient_DO_mass_plot.html")

```

## Metabolic Rate Calculations
### Tank 2; 7C
#### Chamber 16
```{r}
######################## NEP rate calculations

## the linear portion of the NEP curve is roughly from minute 166 to minute 236 ##

pnld_a_16 <- dat_full %>%
  filter(chamber == "16" & delta_T_min >= 166 & delta_T_min <= 236)

pnld_a_16_NEP_mod <- lm(oxygen_mass_mg~delta_T_min, pnld_a_16)
summary(pnld_a_16_NEP_mod)
pnld_a_16_NEP_mod$coefficients[2]
pnld_a_16_NEP_slope <- unname(pnld_a_16_NEP_mod$coefficients[2])

# oxygen mass (mg) = 0.01659 * time(minutes) + 0.2537

## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
pnld_a_16_NEP <- pnld_a_16_NEP_slope * 1440
pnld_a_16_NEP

######################## ER rate calculations

## The linear portion of the ER curve has a very small signal, thus I measured ER from the dark period preceding the NEP portion of the incubation (roughly from minute 117 to minute 166) and averaged this with the ER signal post-NEP period.

pnld_a_16 <- dat_full %>%
  filter(chamber =="16" & delta_T_min >= 117 & delta_T_min <= 166)

pnld_a_16_ER_mod <- lm(oxygen_mass_mg~delta_T_min, pnld_a_16)
summary(pnld_a_16_ER_mod)
pnld_a_16_ER_mod$coefficients[2]
pnld_a_16_ER_slope <- unname(pnld_a_16_ER_mod$coefficients[2])

# oxygen mass (mg) = -0.01045 * time(minutes) + 30.49


## now measuring ER from the period after the NEP portion of the incubation.
pnld_a_16 <- dat_full %>%
  filter(chamber =="16" & delta_T_min >= 249)

pnld_a_16_ER_mod2 <- lm(oxygen_mass_mg~delta_T_min, pnld_a_16)
summary(pnld_a_16_ER_mod2)
pnld_a_16_ER_mod2$coefficients[2]
pnld_a_16_ER_slope2 <- unname(pnld_a_16_ER_mod2$coefficients[2])

# oxygen mass (mg) = -0.00697 * time(minutes) + 29.41

# calculate average of the two ER slopes
pnld_a_16_ER_slope_avg <- (pnld_a_16_ER_slope + pnld_a_16_ER_slope2)/2


## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
pnld_a_16_ER <- pnld_a_16_ER_slope_avg * 1440
pnld_a_16_ER

######################## GPP
pnld_a_16_GPP <- pnld_a_16_NEP - pnld_a_16_ER

# plot of DO in this chamber to check that regressions match with data
pnld_a_16_plot <- dat_full %>%
  filter(chamber == "16") %>%
  filter(delta_T_min > 100) %>%
  ggplot(aes(x = delta_T_min, y = oxygen_mass_mg)) +
  geom_point(shape = 1, size = 2) +
  geom_abline(aes(intercept = pnld_a_16_NEP_mod$coefficients[1], slope = pnld_a_16_NEP_mod$coefficients[2])) +
  geom_abline(aes(intercept = pnld_a_16_ER_mod$coefficients[1], slope = pnld_a_16_ER_mod$coefficients[2])) +
  geom_abline(aes(intercept = pnld_a_16_ER_mod2$coefficients[1], slope = pnld_a_16_ER_mod2$coefficients[2])) +
  theme_classic()
pnld_a_16_plot
```

#### Chamber 15
```{r}
######################## NEP rate calculations

## the linear portion of the NEP curve is roughly from minute 166 to minute 236 ##

pnld_a_15 <- dat_full %>%
  filter(chamber == "15" & delta_T_min >= 166 & delta_T_min <= 236)

pnld_a_15_NEP_mod <- lm(oxygen_mass_mg~delta_T_min, pnld_a_15)
summary(pnld_a_15_NEP_mod)
pnld_a_15_NEP_mod$coefficients[2]
pnld_a_15_NEP_slope <- unname(pnld_a_15_NEP_mod$coefficients[2])

# oxygen mass (mg) = 0.01659 * time(minutes) + 0.2537

## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
pnld_a_15_NEP <- pnld_a_15_NEP_slope * 1440
pnld_a_15_NEP

######################## ER rate calculations

## The linear portion of the ER curve has a very small signal, thus I measured ER from the dark period preceding the NEP portion of the incubation (roughly from minute 117 to minute 166) and averaged this with the ER signal post-NEP period.

pnld_a_15 <- dat_full %>%
  filter(chamber =="15" & delta_T_min >= 117 & delta_T_min <= 166)

pnld_a_15_ER_mod <- lm(oxygen_mass_mg~delta_T_min, pnld_a_15)
summary(pnld_a_15_ER_mod)
pnld_a_15_ER_mod$coefficients[2]
pnld_a_15_ER_slope <- unname(pnld_a_15_ER_mod$coefficients[2])

# oxygen mass (mg) = -0.01045 * time(minutes) + 30.49


## now measuring ER from the period after the NEP portion of the incubation.
pnld_a_15 <- dat_full %>%
  filter(chamber =="15" & delta_T_min >= 249)

pnld_a_15_ER_mod2 <- lm(oxygen_mass_mg~delta_T_min, pnld_a_15)
summary(pnld_a_15_ER_mod2)
pnld_a_15_ER_mod2$coefficients[2]
pnld_a_15_ER_slope2 <- unname(pnld_a_15_ER_mod2$coefficients[2])

# oxygen mass (mg) = -0.00697 * time(minutes) + 29.41

# calculate average of the two ER slopes
pnld_a_15_ER_slope_avg <- (pnld_a_15_ER_slope + pnld_a_15_ER_slope2)/2


## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
pnld_a_15_ER <- pnld_a_15_ER_slope_avg * 1440
pnld_a_15_ER

######################## GPP
pnld_a_15_GPP <- pnld_a_15_NEP - pnld_a_15_ER

# plot of DO in this chamber to check that regressions match with data
pnld_a_15_plot <- dat_full %>%
  filter(chamber == "15") %>%
  ggplot(aes(x = delta_T_min, y = oxygen_mass_mg)) +
  geom_point(shape = 1, size = 2) +
  geom_abline(aes(intercept = pnld_a_15_NEP_mod$coefficients[1], slope = pnld_a_15_NEP_mod$coefficients[2])) +
  geom_abline(aes(intercept = pnld_a_15_ER_mod$coefficients[1], slope = pnld_a_15_ER_mod$coefficients[2])) +
  geom_abline(aes(intercept = pnld_a_15_ER_mod2$coefficients[1], slope = pnld_a_15_ER_mod2$coefficients[2])) +
  theme_classic()
pnld_a_15_plot
```

#### Chamber 13
```{r}
######################## NEP rate calculations

## the linear portion of the NEP curve is roughly from minute 166 to minute 236 ##

pnld_a_13 <- dat_full %>%
  filter(chamber == "13" & delta_T_min >= 166 & delta_T_min <= 236)

pnld_a_13_NEP_mod <- lm(oxygen_mass_mg~delta_T_min, pnld_a_13)
summary(pnld_a_13_NEP_mod)
pnld_a_13_NEP_mod$coefficients[2]
pnld_a_13_NEP_slope <- unname(pnld_a_13_NEP_mod$coefficients[2])

# oxygen mass (mg) = 0.01659 * time(minutes) + 0.2537

## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
pnld_a_13_NEP <- pnld_a_13_NEP_slope * 1440
pnld_a_13_NEP

######################## ER rate calculations

## The linear portion of the ER curve has a very small signal, thus I measured ER from the dark period preceding the NEP portion of the incubation (roughly from minute 117 to minute 166) and averaged this with the ER signal post-NEP period.

pnld_a_13 <- dat_full %>%
  filter(chamber =="13" & delta_T_min >= 117 & delta_T_min <= 166)

pnld_a_13_ER_mod <- lm(oxygen_mass_mg~delta_T_min, pnld_a_13)
summary(pnld_a_13_ER_mod)
pnld_a_13_ER_mod$coefficients[2]
pnld_a_13_ER_slope <- unname(pnld_a_13_ER_mod$coefficients[2])

# oxygen mass (mg) = -0.01045 * time(minutes) + 30.49


## now measuring ER from the period after the NEP portion of the incubation.
pnld_a_13 <- dat_full %>%
  filter(chamber =="13" & delta_T_min >= 249)

pnld_a_13_ER_mod2 <- lm(oxygen_mass_mg~delta_T_min, pnld_a_13)
summary(pnld_a_13_ER_mod2)
pnld_a_13_ER_mod2$coefficients[2]
pnld_a_13_ER_slope2 <- unname(pnld_a_13_ER_mod2$coefficients[2])

# oxygen mass (mg) = -0.00697 * time(minutes) + 29.41

# calculate average of the two ER slopes
pnld_a_13_ER_slope_avg <- (pnld_a_13_ER_slope + pnld_a_13_ER_slope2)/2


## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
pnld_a_13_ER <- pnld_a_13_ER_slope_avg * 1440
pnld_a_13_ER

######################## GPP
pnld_a_13_GPP <- pnld_a_13_NEP - pnld_a_13_ER

# plot of DO in this chamber to check that regressions match with data
pnld_a_13_plot <- dat_full %>%
  filter(chamber == "13") %>%
  ggplot(aes(x = delta_T_min, y = oxygen_mass_mg)) +
  geom_point(shape = 1, size = 2) +
  geom_abline(aes(intercept = pnld_a_13_NEP_mod$coefficients[1], slope = pnld_a_13_NEP_mod$coefficients[2])) +
  geom_abline(aes(intercept = pnld_a_13_ER_mod$coefficients[1], slope = pnld_a_13_ER_mod$coefficients[2])) +
  geom_abline(aes(intercept = pnld_a_13_ER_mod2$coefficients[1], slope = pnld_a_13_ER_mod2$coefficients[2])) +
  theme_classic()
pnld_a_13_plot
```

#### Chamber 4
```{r}
######################## NEP rate calculations

## the linear portion of the NEP curve is roughly from minute 166 to minute 236 ##

pnld_a_4 <- dat_full %>%
  filter(chamber == "4" & delta_T_min >= 166 & delta_T_min <= 236)

pnld_a_4_NEP_mod <- lm(oxygen_mass_mg~delta_T_min, pnld_a_4)
summary(pnld_a_4_NEP_mod)
pnld_a_4_NEP_mod$coefficients[2]
pnld_a_4_NEP_slope <- unname(pnld_a_4_NEP_mod$coefficients[2])

# oxygen mass (mg) = 0.01659 * time(minutes) + 0.2537

## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
pnld_a_4_NEP <- pnld_a_4_NEP_slope * 1440
pnld_a_4_NEP

######################## ER rate calculations

## The linear portion of the ER curve has a very small signal, thus I measured ER from the dark period preceding the NEP portion of the incubation (roughly from minute 117 to minute 166) and averaged this with the ER signal post-NEP period.

pnld_a_4 <- dat_full %>%
  filter(chamber =="4" & delta_T_min >= 117 & delta_T_min <= 166)

pnld_a_4_ER_mod <- lm(oxygen_mass_mg~delta_T_min, pnld_a_4)
summary(pnld_a_4_ER_mod)
pnld_a_4_ER_mod$coefficients[2]
pnld_a_4_ER_slope <- unname(pnld_a_4_ER_mod$coefficients[2])

# oxygen mass (mg) = -0.01045 * time(minutes) + 30.49


## now measuring ER from the period after the NEP portion of the incubation.
pnld_a_4 <- dat_full %>%
  filter(chamber =="4" & delta_T_min >= 249)

pnld_a_4_ER_mod2 <- lm(oxygen_mass_mg~delta_T_min, pnld_a_4)
summary(pnld_a_4_ER_mod2)
pnld_a_4_ER_mod2$coefficients[2]
pnld_a_4_ER_slope2 <- unname(pnld_a_4_ER_mod2$coefficients[2])

# oxygen mass (mg) = -0.00697 * time(minutes) + 29.41

# calculate average of the two ER slopes
pnld_a_4_ER_slope_avg <- (pnld_a_4_ER_slope + pnld_a_4_ER_slope2)/2


## Now converting this rate from mg O2 per minute to per day by multiplying this rate by 1440 minutes per day. ##
pnld_a_4_ER <- pnld_a_4_ER_slope_avg * 1440
pnld_a_4_ER

######################## GPP
pnld_a_4_GPP <- pnld_a_4_NEP - pnld_a_4_ER

# plot of DO in this chamber to check that regressions match with data
pnld_a_4_plot <- dat_full %>%
  filter(chamber == "4") %>%
  ggplot(aes(x = delta_T_min, y = oxygen_mass_mg)) +
  geom_point(shape = 1, size = 2) +
  geom_abline(aes(intercept = pnld_a_4_NEP_mod$coefficients[1], slope = pnld_a_4_NEP_mod$coefficients[2])) +
  geom_abline(aes(intercept = pnld_a_4_ER_mod$coefficients[1], slope = pnld_a_4_ER_mod$coefficients[2])) +
  geom_abline(aes(intercept = pnld_a_4_ER_mod2$coefficients[1], slope = pnld_a_4_ER_mod2$coefficients[2])) +
  theme_classic()
pnld_a_4_plot
```


### Tank 1; 10C

#### Chamber 9
```{r}

```


#### Chamber 2
#### Chamber 11
#### Chamber 6