---
title: "Waterbath Temp Tests"
author: "Nick Framsted"
date: "12/8/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(ggpubr)
# changing working directory from /scripts to /tahoe_lab_inc_analysis
knitr::opts_knit$set(root.dir = '..')
```

# reading in data
```{r, include=FALSE}
getwd()
dat <- read_csv("data/waterbath_temptests_main.csv", skip = 1)
```


# converting date-times in data
```{r}
str(dat)
head(dat)
dat$date_time_PST <- mdy_hms(dat$date_time_GMT_0800, tz = "America/Los_Angeles")
head(dat)

# and adding in day column
dat$day <- day(dat$date_time_PST)

head(dat)

#making tank a factor instead of numeric (it's really a categorical variable)
dat$tank <- as.factor(dat$tank)
```

# Nov 19 experiment
```{r}
# filtering by date time to only include measurements taken during nov 19th and trimming off data taken before start time and after end time of the experiment 
dat_19 <- dat %>%
  filter(date_time_PST > "2020-11-19 14:45:00" & date_time_PST < "2020-11-19 16:30:00")
dat_19 %>%
  ggplot(aes(x = date_time_PST, y = temp_C, color = tank)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation() +
  theme_bw()

# cooling period only
dat_19 <- dat %>%
  filter(date_time_PST > "2020-11-19 14:45:00" & date_time_PST < "2020-11-19 15:30:00")
dat_19 %>%
  ggplot(aes(x = date_time_PST, y = temp_C, color = tank)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation() +
  theme_bw()

# warming period
  dat_19 <- dat %>%
  filter(date_time_PST > "2020-11-19 15:45:00" & date_time_PST < "2020-11-19 16:25:00")
dat_19 %>%
  ggplot(aes(x = date_time_PST, y = temp_C, color = tank)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation() +
  theme_bw()
  
  
```
# conclusions
There is no real difference in cooling when you have lights on or when they are off. Lights on will warm tanks about 1.7 times faster when the heat pump is disengaged. 

# Nov 23 experiment
```{r}
# filtering by date time to only include measurements taken during nov 23th and trimming data, only doing tanks 1 & 3 to analyze light effects on heating.
dat_23 <- dat %>%
  filter(date_time_PST > "2020-11-23 14:00:00" & date_time_PST < "2020-11-23 16:30:00")
dat_23 %>%
  ggplot(aes(x = date_time_PST, y = temp_C, color = container)) +
  facet_wrap(~tank) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation() +
  theme_bw()
```

